[build]
  base = "."
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.1"
  NPM_VERSION = "9.8.1"
  NODE_OPTIONS = "--max_old_space_size=4096"

# Remove Next.js plugin since we're using Rsbuild
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 